# Site settings
# title: ""
description: An analysis of major power outages across the United States from 2004 to 2016
theme: jekyll-theme-cayman  # Use this or choose one theme, not both
markdown: kramdown
baseurl: "/Power_Outage_Analysis"  # Ensure this matches your GitHub repo path
url: "https://andiigonzalez.github.io"  # your GitHub Pages URL will be automatically set

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - _layouts/default.html
  - _layouts/authors.html
  - assets/images/header_image.jpeg

# Navigation
navigation:
  - text: Home
    link: "{{ site.baseurl }}/index"
  - text: Citations
    link: "{{ site.baseurl }}/citations"
  - text: Other Resources
    link: "{{ site.baseurl }}/resources"
  - text: About Us
    link: "{{ site.baseurl }}/about"

header:
  image: "{{ site.baseurl }}/assets/images/header_image.jpeg"
  caption: Powering Through
