# Site settings
title: Power Outage Analysis
description: Analysis of power outages and their impacts
baseurl: "/Power_Outage_Analysis"
url: ""  # your GitHub Pages URL will be automatically set

# Theme settings
remote_theme: hexagon/lumocs
markdown: kramdown

# Navigation
navigation:
  - text: Home
    link: /
  - text: About
    link: /about

# Theme customization
lumocs:
  color_scheme: dark  # or 'light'
  syntax_highlight: true
  sidebar: true
  search: true
