# Site settings
title: Powering Through
description: Analyzing Trends in Major US Power Outages from 2004 to 2016
baseurl: "/Power_Outage_Analysis"
url: "https://andiigonzalez.github.io"  # your GitHub Pages URL will be automatically set

# Theme settings
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
include:
  - assets/css/custom.css

# Navigation
navigation:
  - text: Home
    link: /index
  - text: Emergency Resources
    link: /emergency
  - text: Citations
    link: /citations
